# Default values for bff.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
image:
  repository: <your docker private registry>/bff
nameOverride: "bff"
fullnameOverride: "bff"
service:
  type: ClusterIP
  port: 8888
# Additional volumes on the output Deployment definition.
volumes:
  - name: tls-server
    csi:
      readOnly: true
      driver: csi.cert-manager.io
      volumeAttributes:
        csi.cert-manager.io/issuer-name: "moke-root-ca"
        csi.cert-manager.io/dns-names: ${POD_NAME}.${POD_NAMESPACE}.svc.cluster.local
        csi.cert-manager.io/issuer-kind: "AWSPCAClusterIssuer"
        csi.cert-manager.io/issuer-group: "awspca.cert-manager.io"
        csi.cert-manager.io/common-name: "${SERVICE_ACCOUNT_NAME}.${POD_NAMESPACE}"
        csi.cert-manager.io/duration: "168h"
        csi.cert-manager.io/renew-before: "1h"
  - name: tls-client
    csi:
      readOnly: true
      driver: csi.cert-manager.io
      volumeAttributes:
        csi.cert-manager.io/issuer-name: "moke-root-ca"
        csi.cert-manager.io/issuer-kind: "AWSPCAClusterIssuer"
        csi.cert-manager.io/issuer-group: "awspca.cert-manager.io"
        csi.cert-manager.io/common-name: "${SERVICE_ACCOUNT_NAME}.${POD_NAMESPACE}"
        csi.cert-manager.io/duration: "168h"
        csi.cert-manager.io/renew-before: "1h"
  - name: iap-secrets
    secret:
      secretName: iap
# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: tls-client
    mountPath: "/configs/tls-client"
    readOnly: true
  - name: tls-server
    mountPath: "configs/tls-server"
    readOnly: true
  - name: iap-secrets
    mountPath: "/configs/iap"
    readOnly: true
env:
  - name: "ANALYTICS_URL"
    value: "analytics.default.svc.cluster.local:8081"
  - name: "CASHBATTLE_URL"
    value: "activity.default.svc.cluster.local:8081"
  - name: "GM_URL"
    value: "gm.default.svc.cluster.local:8081"
  - name: "BUDDY_URL"
    value: "buddy.default.svc.cluster.local:8081"
  - name: "CHAT_URL"
    value: "chat.default.svc.cluster.local:8081"
  - name: "KNAPSACK_URL"
    value: "knapsack.default.svc.cluster.local:8081"
  - name: "MATCH_URL"
    value: "matchmaking.default.svc.cluster.local:8081"
  - name: "PARTY_URL"
    value: "party.default.svc.cluster.local:8081"
  - name: "PROFILE_URL"
    value: "profile.default.svc.cluster.local:8081"
  - name: "MAIL_URL"
    value: "mail.default.svc.cluster.local:8081"
  - name: "LEADERBOARD_URL"
    value: "leaderboard.default.svc.cluster.local:8081"
  - name: APPLE_SANDBOX
    value: "false"
  - name: APPLE_PRIVATE_KEY
    value: "./configs/iap/apple_key.p8"
  - name: GOOGLE_PLAY_PUBLIC_KEY
    value: "./configs/iap/google_key.json"
  - name: APPLE_KEY_ID
    valueFrom:
      secretKeyRef:
        name: iap
        key: apple-key-id
  - name: APPLE_ISSUER
    valueFrom:
      secretKeyRef:
        name: iap
        key: apple-issuer
  - name: APPLE_BUNDLE_ID
    valueFrom:
      secretKeyRef:
        name: iap
        key: apple-bundle-id