apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: allocator-tls
  namespace: agones-system
spec:
  commonName: agones-allocator
  dnsNames:
    - "agones-allocator.agones-system.svc.cluster.local"
  duration: 168h0m0s
  issuerRef:
    group: awspca.cert-manager.io
    kind: AWSPCAClusterIssuer
    name: moke-root-ca
  renewBefore: 1h0m0s
  secretName: allocator-tls