apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-cert-2048
  namespace: default
spec:
  commonName: moke.service.com
  dnsNames:
    - "*.yourhost.com"
  duration: 168h0m0s
  issuerRef:
    group: awspca.cert-manager.io
    kind: AWSPCAClusterIssuer
    name: moke-root-ca
  renewBefore: 1h0m0s
  secretName: platform-cert-2048
  usages:
    - server auth
    - client auth
  privateKey:
    algorithm: "RSA"
    size: 2048